# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 03:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171128_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 29, 19, 17, 57, 818509)),
        ),
    ]
