# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 03:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171129_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 29, 19, 46, 14, 75743)),
        ),
    ]
