# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-14 23:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20171130_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 1, 14, 15, 28, 7, 570002)),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/media-root/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='text',
            field=models.CharField(max_length=5000),
        ),
    ]
