# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 00:32
from __future__ import unicode_literals

import api.models
import api.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20180114_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=api.storage.OverwriteStorage(), upload_to=api.models.customImagePath),
        ),
    ]
