# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 07:40
from __future__ import unicode_literals

import api.models
import api.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20180115_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=api.storage.OverwriteStorage(), upload_to=api.models.vueProjectAssetPath),
        ),
    ]
