# Generated by Django 2.0.1 on 2018-01-19 07:14

import api.models
import api.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20180115_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=api.storage.OverwriteStorage(), upload_to=api.models.customImagePath),
        ),
    ]
